version: Build-{build}
os: Visual Studio 2019
environment:
  version: 2
  matrix:
    - TRIPLET: x86-windows-static
    - TRIPLET: x64-windows-static
#    - TRIPLET: x86-uwp
#    - TRIPLET: x64-uwp
#    - TRIPLET: arm-uwp
#    - TRIPLET: arm-windows
#    - TRIPLET: arm64-windows
#    - TRIPLET: arm64-uwp
install:
- cmd: install.bat
build_script:
- cmd: >-
    build.bat

    package.bat

test: off
artifacts:
- path: '**\simutrans*.zip'
  name: Zip simplified archive
- path: '**\vcpkg*.zip'
  name: Zip vcpkg archive
- path: '**\vcpkg*.nupkg'
  name: NuGet vcpkg archive
deploy:
  provider: GitHub
  auth_token:
    secure: 1xGzHXZLbohOoeETDIaYivZv3s910v6nxsXBSNoTNWWy4UBsmmxUjikVxdHsLRDY
  artifact: Zip simplified archive
  draft: true
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
